# Generated by Django 4.2.16 on 2026-09-07 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0002_skillgapanalysis_skillrequirement'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspiring_students', to='career.careerpath'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='proficiency_score',
            field=models.PositiveIntegerField(default=50, help_text='Exact proficiency percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='source',
            field=models.CharField(default='self', help_text='Source: self, assessment, quiz, course, resume, ai', max_length=50),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_name', models.CharField(blank=True, default='', max_length=255)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('breakdown_scores', models.JSONField(default=dict, help_text='Scores for skills, experience, education, projects, formatting')),
                ('extracted_skills', models.JSONField(default=list)),
                ('normalized_skills', models.JSONField(default=list)),
                ('extracted_education', models.JSONField(default=list)),
                ('extracted_experience', models.JSONField(default=list)),
                ('extracted_projects', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('career_alignment', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
