# Generated by Django 4.2.16 on 2026-09-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0002_skillgapanalysis_skillrequirement'),
        ('students', '0002_studentprofile_target_career_and_more'),
        ('learning', '0003_learningroadmap_studentgamification_roadmapitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='students.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='learning.subject')),
            ],
            options={
                'ordering': ['completed', 'scheduled_date', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conducting_body', models.CharField(help_text='e.g. NTA, IITs, NBE, UPSC', max_length=255)),
                ('exam_category', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('management', 'Management'), ('civil_services', 'Civil Services'), ('law', 'Law'), ('sciences', 'Sciences & Research'), ('other', 'Other')], default='engineering', max_length=50)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria & educational qualifications', null=True)),
                ('application_period', models.CharField(blank=True, help_text='Application window or dates e.g. Dec - Jan (Annual)', max_length=255, null=True)),
                ('exam_date_reference', models.CharField(blank=True, help_text='Expected exam window / reference date', max_length=255, null=True)),
                ('official_website', models.URLField(blank=True, help_text='Official exam portal', null=True)),
                ('registration_url', models.URLField(blank=True, help_text='Direct registration link if active', null=True)),
                ('exam_pattern', models.TextField(blank=True, help_text='Format: Mode (CBT/Offline), Duration, Sections, Marking scheme', null=True)),
                ('syllabus_summary', models.TextField(blank=True, help_text='Key subjects and high-weightage topics covered', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_career_paths', models.ManyToManyField(blank=True, related_name='entrance_exams', to='career.careerpath')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
