# Generated by Django 4.2.16 on 2026-09-07 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.DecimalField(decimal_places=2, default=0, help_text='Overall Career Readiness 0-100%', max_digits=5)),
                ('total_skills_count', models.PositiveIntegerField(default=0)),
                ('strong_count', models.PositiveIntegerField(default=0)),
                ('minor_count', models.PositiveIntegerField(default=0)),
                ('moderate_count', models.PositiveIntegerField(default=0)),
                ('major_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('gaps_data', models.JSONField(default=list, help_text='Detailed skill-by-skill comparisons')),
                ('priority_skills', models.JSONField(default=list, help_text='Ordered top priority skills to learn next')),
                ('category_summary', models.JSONField(default=dict, help_text='Category-level readiness breakdown for charts')),
                ('ai_explanation', models.TextField(blank=True, help_text='Explainability & personalized next steps', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to='career.careerpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.PositiveIntegerField(default=75, help_text='Required proficiency score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('importance', models.PositiveIntegerField(default=4, help_text='Importance weight (1: Optional, 3: Important, 5: Critical)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_core', models.BooleanField(default=True, help_text='Is this a core mandatory skill for this role')),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='career.careerpath')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements', to='students.skill')),
            ],
            options={
                'ordering': ['-importance', '-required_proficiency'],
                'unique_together': {('career_path', 'skill')},
            },
        ),
    ]
